// app/api/websites/create/route.ts
// Unified creation: every new website/app becomes a REAL saved record that
// immediately appears in "My Sites & Apps" as a draft with a Publish button.
//
//   business | creative   → builder-backed registry record (createBuilderWebsite)
//   invitational | pov_event → pov_events row + linked registry record
export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { getUserContext } from '@/lib/auth/getUserContext'
import { getSupabaseServerClient } from '@/lib/supabase/server'
import { sanitizeTenantId } from '@/lib/website/resolveWebsiteTenant'
import { createPovEventRecord } from '@/lib/pov/createEvent'
import {
  createBuilderWebsite, getWebsite, getPrimaryBuilderWebsite, withUrls, checkSlugAvailable,
  type WebsiteRecord, type WebsiteType, type WebsiteWithUrl,
} from '@/lib/website/registry'

function forbidden() { return NextResponse.json({ error: 'Forbidden' }, { status: 403 }) }

function resolveTenantId(ctx: Awaited<ReturnType<typeof getUserContext>>, override?: string | null): string | null {
  if (!ctx) return null
  const hint = sanitizeTenantId(override)
  const self = sanitizeTenantId(ctx.tenant_id)
  if (ctx.role === 'owner') return hint ?? self
  if (self && hint && self !== hint) return null
  return self ?? hint
}

function descriptor(w: WebsiteWithUrl) {
  return {
    websiteId: w.id,
    websiteType: w.website_type,
    publicSlug: w.public_slug,
    status: w.status,
    editUrl: w.edit_url,
    liveUrl: w.status === 'published' ? w.public_url : null,
    draftPreviewUrl: w.preview_url,
    povEventId: w.pov_event_id,
    canvaImportId: w.canva_import_id,
  }
}

export async function POST(req: NextRequest) {
  const ctx = await getUserContext()
  if (!ctx || !['owner', 'admin'].includes(ctx.role)) return forbidden()

  const body = await req.json().catch(() => ({})) as Record<string, unknown>
  const tenantId = resolveTenantId(ctx, body.tenantId as string ?? body.tenant_id as string)
  if (!tenantId) return NextResponse.json({ error: 'No tenant' }, { status: 400 })

  const websiteType = (['business', 'creative', 'invitational', 'pov_event'].includes(body.websiteType as string)
    ? body.websiteType : 'business') as WebsiteType
  const name = String(body.name ?? '').trim()
  const povEnabled = Boolean(body.povEnabled)

  // ── Builder-backed business / creative website ──────────────────────────────
  // One builder site exists per tenant. If the primary already exists (auto-
  // ensured), configure it instead of creating a confusing duplicate that would
  // share the same builder content.
  if (websiteType === 'business' || websiteType === 'creative') {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const db = getSupabaseServerClient() as any
    let site: WebsiteWithUrl | null = await getPrimaryBuilderWebsite(tenantId)

    if (site) {
      const update: Record<string, unknown> = { website_type: websiteType }
      if (name) update.name = name
      if (typeof body.canvaImportId === 'string' && body.canvaImportId) {
        update.canva_import_enabled = true
        update.canva_import_id = body.canvaImportId
      }
      await db.from('websites').update(update).eq('tenant_id', tenantId).eq('id', site.id)
      site = await getWebsite(tenantId, site.id)
    } else {
      const result = await createBuilderWebsite({
        tenantId, websiteType, name: name || 'My Website',
        slug: String(body.publicSlug ?? body.slug ?? name ?? ''),
        createdBy: ctx.id ?? null,
      })
      if (result.error || !result.website) return NextResponse.json({ error: result.error ?? 'Create failed' }, { status: 400 })
      site = result.website
    }

    // Keep the legacy builder branch in sync so the editor renders this type.
    try {
      await db.from('site_settings')
        .upsert({ tenant_id: tenantId, website_type: websiteType }, { onConflict: 'tenant_id' })
    } catch { /* non-fatal */ }

    if (!site) return NextResponse.json({ error: 'Could not resolve website record.' }, { status: 500 })
    return NextResponse.json({ ...descriptor(site) }, { status: 201 })
  }

  // ── Event-backed invitational / POV website ─────────────────────────────────
  if (!name) return NextResponse.json({ error: 'A name is required.' }, { status: 400 })

  // If a slug was supplied, validate it (the event slug itself is generated by
  // createPovEventRecord, but we surface reserved/format errors early).
  if (body.publicSlug) {
    const check = await checkSlugAvailable(tenantId, String(body.publicSlug))
    if (!check.available) return NextResponse.json({ error: check.reason }, { status: 400 })
  }

  const created = await createPovEventRecord({
    tenantId,
    name,
    websiteType: websiteType === 'invitational' ? 'invitational' : 'pov_event',
    createdBy: ctx.id ?? null,
    event_type: body.eventType as string | undefined,
    event_date: (body.eventDate as string) ?? null,
    gallery_reveal_at: (body.galleryRevealAt as string) ?? null,
    timezone: body.timezone as string | undefined,
    theme_key: body.themeKey as string | undefined,
    ...(body.povEventSetup as Record<string, unknown> ?? {}),
  })
  if (created.error || !created.event) return NextResponse.json({ error: created.error ?? 'Create failed' }, { status: 400 })

  // Resolve the registry row that ensureWebsiteRegistry created for this event.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = getSupabaseServerClient() as any
  const { data: row } = await db.from('websites').select('*')
    .eq('tenant_id', tenantId).eq('pov_event_id', created.event.id).maybeSingle()

  // Attach a Canva import to THIS event website only (never the business site).
  if (row && typeof body.canvaImportId === 'string' && body.canvaImportId) {
    await db.from('websites').update({ canva_import_enabled: true, canva_import_id: body.canvaImportId })
      .eq('tenant_id', tenantId).eq('id', row.id)
    row.canva_import_enabled = true
    row.canva_import_id = body.canvaImportId
  }

  const site = row ? withUrls(row as WebsiteRecord) : await getWebsite(tenantId, created.event.id)
  if (!site) return NextResponse.json({ error: 'Created event but could not resolve its website record.' }, { status: 500 })

  void povEnabled
  return NextResponse.json({ ...descriptor(site), povEventId: created.event.id }, { status: 201 })
}
