// lib/website/design/categoryPresets.ts
// Business-category-specific design presets for the AI website design system.

import type { CategoryPreset } from './types'

const PRESETS: CategoryPreset[] = [
  // ── Food & Beverage ────────────────────────────────────────────────────────
  {
    category: 'restaurant',
    aliases:  ['dining', 'bistro', 'eatery', 'diner', 'grill', 'steakhouse'],
    mood:     'warm, appetizing, welcoming, upscale casual',
    designLevel: 'warm',
    palette: {
      primary:       '#C0392B',
      secondary:     '#E67E22',
      accent:        '#F1C40F',
      background:    '#FFFBF7',
      surface:       '#FFF5EE',
      surfaceAlt:    '#FDF0E6',
      textPrimary:   '#1A0E0A',
      textSecondary: '#5C3D2E',
      mutedText:     '#8B6654',
      border:        '#E8D5C4',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(192,57,43,0.85) 0%, rgba(230,126,34,0.75) 100%)',
      sectionSoft: 'linear-gradient(180deg, #FFF5EE 0%, #FFFBF7 100%)',
      accentWash:  'linear-gradient(135deg, #FDF0E6 0%, #FFF5EE 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(26,14,10,0.65) 0%, rgba(26,14,10,0.4) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(255,245,238,0.7) 0%, rgba(255,245,238,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'serif',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Playfair Display', 'Georgia', serif",
      bodyFontStack:       "'Lato', 'Open Sans', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.65',
    },
    radius:  { card: '1rem',    button: '0.75rem', image: '1.25rem', section: '0' },
    shadows: {
      card:     '0 4px 24px rgba(192,57,43,0.08)',
      floating: '0 8px 40px rgba(192,57,43,0.15)',
      image:    '0 16px 48px rgba(26,14,10,0.18)',
      button:   '0 4px 16px rgba(192,57,43,0.25)',
    },
    layout: {
      maxWidth:              '1200px',
      sectionPaddingDesktop: '6rem 1.5rem',
      sectionPaddingMobile:  '4rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'curved',
      dividerStyle:       'wave',
      backgroundStrategy: 'alternating_soft',
    },
  },
  {
    category: 'cafe',
    aliases:  ['coffee', 'coffee shop', 'espresso', 'coffee house', 'coffeehouse'],
    mood:     'cozy, artisan, warm, community',
    designLevel: 'warm',
    palette: {
      primary:       '#6B3F1F',
      secondary:     '#A67C52',
      accent:        '#D4A76A',
      background:    '#FBF8F4',
      surface:       '#F5EFE6',
      surfaceAlt:    '#EDE3D6',
      textPrimary:   '#2C1810',
      textSecondary: '#6B4F3A',
      mutedText:     '#9C7B65',
      border:        '#E0D0C0',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(107,63,31,0.80) 0%, rgba(166,124,82,0.70) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F5EFE6 0%, #FBF8F4 100%)',
      accentWash:  'linear-gradient(135deg, #EDE3D6 0%, #F5EFE6 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(44,24,16,0.65) 0%, rgba(44,24,16,0.35) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(251,248,244,0.75) 0%, rgba(251,248,244,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'serif',
      bodyFontCategory:    'humanist',
      headingFontStack:    "'Libre Baskerville', 'Georgia', serif",
      bodyFontStack:       "'Nunito', 'Open Sans', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.7',
    },
    radius:  { card: '1.25rem', button: '2rem',   image: '1.5rem',  section: '0' },
    shadows: {
      card:     '0 2px 16px rgba(107,63,31,0.08)',
      floating: '0 8px 32px rgba(107,63,31,0.14)',
      image:    '0 12px 40px rgba(44,24,16,0.15)',
      button:   '0 4px 12px rgba(107,63,31,0.2)',
    },
    layout: {
      maxWidth:              '1100px',
      sectionPaddingDesktop: '5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'airy',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'soft_blend',
      dividerStyle:       'curve',
      backgroundStrategy: 'alternating_soft',
    },
  },
  {
    category: 'bakery',
    aliases:  ['pastry', 'patisserie', 'bread', 'dessert', 'cake'],
    mood:     'sweet, artisan, feminine, warm',
    designLevel: 'warm',
    palette: {
      primary:       '#D97AAB',
      secondary:     '#E8A87C',
      accent:        '#F5C9A0',
      background:    '#FFF9FB',
      surface:       '#FFF0F5',
      surfaceAlt:    '#FFE8F0',
      textPrimary:   '#2D1B26',
      textSecondary: '#7A4060',
      mutedText:     '#B87090',
      border:        '#F0D8E5',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(217,122,171,0.80) 0%, rgba(232,168,124,0.70) 100%)',
      sectionSoft: 'linear-gradient(180deg, #FFF0F5 0%, #FFF9FB 100%)',
      accentWash:  'linear-gradient(135deg, #FFE8F0 0%, #FFF0F5 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(45,27,38,0.60) 0%, rgba(45,27,38,0.30) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(255,249,251,0.75) 0%, rgba(255,249,251,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'display',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Cormorant Garamond', 'Georgia', serif",
      bodyFontStack:       "'Raleway', 'Helvetica Neue', sans-serif",
      headingWeight:       600,
      letterSpacing:       '0.01em',
      lineHeight:          '1.7',
    },
    radius:  { card: '1.5rem', button: '2rem',   image: '1.5rem', section: '0' },
    shadows: {
      card:     '0 4px 20px rgba(217,122,171,0.10)',
      floating: '0 8px 36px rgba(217,122,171,0.18)',
      image:    '0 12px 40px rgba(45,27,38,0.12)',
      button:   '0 4px 14px rgba(217,122,171,0.28)',
    },
    layout: {
      maxWidth:              '1100px',
      sectionPaddingDesktop: '5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'airy',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'curved',
      dividerStyle:       'wave',
      backgroundStrategy: 'alternating_soft',
    },
  },

  // ── Professional Services ──────────────────────────────────────────────────
  {
    category: 'law firm',
    aliases:  ['attorney', 'lawyer', 'legal', 'law office', 'solicitor'],
    mood:     'trustworthy, authoritative, refined, professional',
    designLevel: 'premium',
    palette: {
      primary:       '#1B3A5C',
      secondary:     '#2E6DA4',
      accent:        '#C4A24E',
      background:    '#FAFBFC',
      surface:       '#F2F5F8',
      surfaceAlt:    '#E8EDF3',
      textPrimary:   '#0D1F31',
      textSecondary: '#3A5068',
      mutedText:     '#6B8097',
      border:        '#D4DDE7',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(27,58,92,0.88) 0%, rgba(46,109,164,0.78) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F2F5F8 0%, #FAFBFC 100%)',
      accentWash:  'linear-gradient(135deg, #E8EDF3 0%, #F2F5F8 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(13,31,49,0.72) 0%, rgba(13,31,49,0.45) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(250,251,252,0.75) 0%, rgba(250,251,252,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'serif',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Merriweather', 'Georgia', serif",
      bodyFontStack:       "'Source Sans Pro', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.015em',
      lineHeight:          '1.65',
    },
    radius:  { card: '0.5rem', button: '0.375rem', image: '0.5rem', section: '0' },
    shadows: {
      card:     '0 2px 12px rgba(13,31,49,0.07)',
      floating: '0 6px 28px rgba(13,31,49,0.12)',
      image:    '0 10px 36px rgba(13,31,49,0.14)',
      button:   '0 2px 10px rgba(27,58,92,0.20)',
    },
    layout: {
      maxWidth:              '1200px',
      sectionPaddingDesktop: '6rem 1.5rem',
      sectionPaddingMobile:  '4rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'editorial',
      dividerStyle:       'angle',
      backgroundStrategy: 'layered_surfaces',
    },
  },
  {
    category: 'medical',
    aliases:  ['doctor', 'clinic', 'hospital', 'healthcare', 'physician', 'practice'],
    mood:     'clean, trustworthy, calm, professional',
    designLevel: 'clean',
    palette: {
      primary:       '#0070C0',
      secondary:     '#00A3BF',
      accent:        '#00C2A8',
      background:    '#F8FAFB',
      surface:       '#EEF4F9',
      surfaceAlt:    '#E2EDF5',
      textPrimary:   '#0A1F33',
      textSecondary: '#2A5075',
      mutedText:     '#6A8FA8',
      border:        '#C8DCEA',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(0,112,192,0.85) 0%, rgba(0,163,191,0.75) 100%)',
      sectionSoft: 'linear-gradient(180deg, #EEF4F9 0%, #F8FAFB 100%)',
      accentWash:  'linear-gradient(135deg, #E2EDF5 0%, #EEF4F9 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(10,31,51,0.68) 0%, rgba(10,31,51,0.40) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(248,250,251,0.75) 0%, rgba(248,250,251,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'sans',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Poppins', 'Helvetica Neue', sans-serif",
      bodyFontStack:       "'Inter', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.65',
    },
    radius:  { card: '0.875rem', button: '0.5rem', image: '1rem', section: '0' },
    shadows: {
      card:     '0 2px 14px rgba(0,112,192,0.07)',
      floating: '0 6px 30px rgba(0,112,192,0.12)',
      image:    '0 10px 36px rgba(10,31,51,0.12)',
      button:   '0 3px 12px rgba(0,112,192,0.22)',
    },
    layout: {
      maxWidth:              '1200px',
      sectionPaddingDesktop: '5.5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'soft_blend',
      dividerStyle:       'curve',
      backgroundStrategy: 'alternating_soft',
    },
  },

  // ── Beauty & Wellness ──────────────────────────────────────────────────────
  {
    category: 'beauty salon',
    aliases:  ['hair salon', 'nail salon', 'beauty', 'hair', 'stylist', 'salon'],
    mood:     'elegant, feminine, luxurious, self-care',
    designLevel: 'luxury',
    palette: {
      primary:       '#8B5E7A',
      secondary:     '#C49BAD',
      accent:        '#E8C4D2',
      background:    '#FDF8FA',
      surface:       '#F8F0F5',
      surfaceAlt:    '#F0E4EC',
      textPrimary:   '#2A1320',
      textSecondary: '#7A4060',
      mutedText:     '#B087A0',
      border:        '#EDD8E8',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(139,94,122,0.82) 0%, rgba(196,155,173,0.72) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F8F0F5 0%, #FDF8FA 100%)',
      accentWash:  'linear-gradient(135deg, #F0E4EC 0%, #F8F0F5 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(42,19,32,0.65) 0%, rgba(42,19,32,0.38) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(253,248,250,0.8) 0%, rgba(253,248,250,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'display',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Cormorant Garamond', 'Georgia', serif",
      bodyFontStack:       "'Raleway', 'Helvetica Neue', sans-serif",
      headingWeight:       600,
      letterSpacing:       '0.02em',
      lineHeight:          '1.75',
    },
    radius:  { card: '1.5rem', button: '2rem', image: '2rem', section: '0' },
    shadows: {
      card:     '0 4px 24px rgba(139,94,122,0.09)',
      floating: '0 10px 40px rgba(139,94,122,0.16)',
      image:    '0 14px 48px rgba(42,19,32,0.13)',
      button:   '0 4px 16px rgba(139,94,122,0.26)',
    },
    layout: {
      maxWidth:              '1100px',
      sectionPaddingDesktop: '6rem 1.5rem',
      sectionPaddingMobile:  '4rem 1.25rem',
      verticalRhythm:        'luxury',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'curved',
      dividerStyle:       'wave',
      backgroundStrategy: 'alternating_soft',
    },
  },
  {
    category: 'spa',
    aliases:  ['wellness', 'massage', 'relaxation', 'retreat', 'therapy'],
    mood:     'serene, luxurious, calming, premium',
    designLevel: 'luxury',
    palette: {
      primary:       '#4A7B6F',
      secondary:     '#82B4AA',
      accent:        '#C9E4E0',
      background:    '#F4FAF9',
      surface:       '#EBF5F3',
      surfaceAlt:    '#DCF0EC',
      textPrimary:   '#1A2F2B',
      textSecondary: '#3A6055',
      mutedText:     '#7AA89F',
      border:        '#CCE6E2',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(74,123,111,0.82) 0%, rgba(130,180,170,0.72) 100%)',
      sectionSoft: 'linear-gradient(180deg, #EBF5F3 0%, #F4FAF9 100%)',
      accentWash:  'linear-gradient(135deg, #DCF0EC 0%, #EBF5F3 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(26,47,43,0.65) 0%, rgba(26,47,43,0.35) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(244,250,249,0.80) 0%, rgba(244,250,249,0.4) 100%)',
    },
    typography: {
      headingFontCategory: 'serif',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Libre Baskerville', 'Georgia', serif",
      bodyFontStack:       "'Lato', 'Open Sans', sans-serif",
      headingWeight:       600,
      letterSpacing:       '0.02em',
      lineHeight:          '1.8',
    },
    radius:  { card: '1.5rem', button: '2rem', image: '2rem', section: '0' },
    shadows: {
      card:     '0 4px 24px rgba(74,123,111,0.08)',
      floating: '0 10px 40px rgba(74,123,111,0.14)',
      image:    '0 14px 48px rgba(26,47,43,0.12)',
      button:   '0 4px 14px rgba(74,123,111,0.22)',
    },
    layout: {
      maxWidth:              '1100px',
      sectionPaddingDesktop: '7rem 1.5rem',
      sectionPaddingMobile:  '4.5rem 1.25rem',
      verticalRhythm:        'luxury',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'soft_blend',
      dividerStyle:       'wave',
      backgroundStrategy: 'alternating_soft',
    },
  },
  {
    category: 'fitness',
    aliases:  ['gym', 'personal trainer', 'crossfit', 'yoga', 'pilates', 'sports', 'athletic'],
    mood:     'energetic, motivating, bold, strong',
    designLevel: 'bold',
    palette: {
      primary:       '#E84C3D',
      secondary:     '#2C3E50',
      accent:        '#F39C12',
      background:    '#FAFAFA',
      surface:       '#F0F0F0',
      surfaceAlt:    '#E5E5E5',
      textPrimary:   '#111111',
      textSecondary: '#333333',
      mutedText:     '#666666',
      border:        '#DDDDDD',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(232,76,61,0.88) 0%, rgba(44,62,80,0.80) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F0F0F0 0%, #FAFAFA 100%)',
      accentWash:  'linear-gradient(135deg, #E5E5E5 0%, #F0F0F0 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(17,17,17,0.72) 0%, rgba(17,17,17,0.45) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(250,250,250,0.70) 0%, rgba(250,250,250,0.35) 100%)',
    },
    typography: {
      headingFontCategory: 'sans',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Oswald', 'Impact', sans-serif",
      bodyFontStack:       "'Roboto', 'Helvetica Neue', sans-serif",
      headingWeight:       800,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.55',
    },
    radius:  { card: '0.75rem', button: '0.5rem', image: '0.75rem', section: '0' },
    shadows: {
      card:     '0 2px 12px rgba(17,17,17,0.08)',
      floating: '0 8px 32px rgba(17,17,17,0.14)',
      image:    '0 12px 40px rgba(17,17,17,0.20)',
      button:   '0 4px 14px rgba(232,76,61,0.28)',
    },
    layout: {
      maxWidth:              '1300px',
      sectionPaddingDesktop: '5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'compact',
      cardDensity:           'compact',
    },
    sectionFlow: {
      style:              'angled',
      dividerStyle:       'angle',
      backgroundStrategy: 'layered_surfaces',
    },
  },

  // ── Home Services ──────────────────────────────────────────────────────────
  {
    category: 'construction',
    aliases:  ['builder', 'contractor', 'remodeling', 'renovation', 'roofing', 'general contractor'],
    mood:     'strong, dependable, professional, bold',
    designLevel: 'bold',
    palette: {
      primary:       '#E85A1A',
      secondary:     '#2C3E50',
      accent:        '#F0A500',
      background:    '#F8F8F6',
      surface:       '#EDEDED',
      surfaceAlt:    '#E0E0DC',
      textPrimary:   '#0D0D0D',
      textSecondary: '#2C2C2C',
      mutedText:     '#6E6E6E',
      border:        '#D4D4CE',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(232,90,26,0.88) 0%, rgba(44,62,80,0.80) 100%)',
      sectionSoft: 'linear-gradient(180deg, #EDEDED 0%, #F8F8F6 100%)',
      accentWash:  'linear-gradient(135deg, #E0E0DC 0%, #EDEDED 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(13,13,13,0.72) 0%, rgba(13,13,13,0.45) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(248,248,246,0.72) 0%, rgba(248,248,246,0.40) 100%)',
    },
    typography: {
      headingFontCategory: 'sans',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Oswald', 'Arial Black', sans-serif",
      bodyFontStack:       "'Roboto', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.55',
    },
    radius:  { card: '0.5rem', button: '0.375rem', image: '0.5rem', section: '0' },
    shadows: {
      card:     '0 2px 10px rgba(13,13,13,0.08)',
      floating: '0 6px 28px rgba(13,13,13,0.14)',
      image:    '0 10px 36px rgba(13,13,13,0.18)',
      button:   '0 4px 12px rgba(232,90,26,0.26)',
    },
    layout: {
      maxWidth:              '1300px',
      sectionPaddingDesktop: '5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'angled',
      dividerStyle:       'angle',
      backgroundStrategy: 'alternating_soft',
    },
  },
  {
    category: 'auto repair',
    aliases:  ['mechanic', 'auto shop', 'auto service', 'car repair', 'tire', 'automotive'],
    mood:     'bold, dependable, technical, confident',
    designLevel: 'bold',
    palette: {
      primary:       '#1A5BA8',
      secondary:     '#E84C2A',
      accent:        '#F0B400',
      background:    '#F5F7FA',
      surface:       '#E8ECF0',
      surfaceAlt:    '#D8DDE5',
      textPrimary:   '#050F1E',
      textSecondary: '#1E3250',
      mutedText:     '#5C7085',
      border:        '#C8D4E0',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(26,91,168,0.88) 0%, rgba(232,76,42,0.78) 100%)',
      sectionSoft: 'linear-gradient(180deg, #E8ECF0 0%, #F5F7FA 100%)',
      accentWash:  'linear-gradient(135deg, #D8DDE5 0%, #E8ECF0 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(5,15,30,0.72) 0%, rgba(5,15,30,0.45) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(245,247,250,0.72) 0%, rgba(245,247,250,0.40) 100%)',
    },
    typography: {
      headingFontCategory: 'sans',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Oswald', 'Arial Black', sans-serif",
      bodyFontStack:       "'Open Sans', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.55',
    },
    radius:  { card: '0.5rem', button: '0.375rem', image: '0.5rem', section: '0' },
    shadows: {
      card:     '0 2px 12px rgba(5,15,30,0.08)',
      floating: '0 6px 28px rgba(5,15,30,0.14)',
      image:    '0 10px 36px rgba(5,15,30,0.18)',
      button:   '0 4px 14px rgba(26,91,168,0.26)',
    },
    layout: {
      maxWidth:              '1300px',
      sectionPaddingDesktop: '5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'compact',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'angled',
      dividerStyle:       'angle',
      backgroundStrategy: 'layered_surfaces',
    },
  },

  // ── Tech / SaaS ────────────────────────────────────────────────────────────
  {
    category: 'tech',
    aliases:  ['technology', 'software', 'IT', 'app', 'startup', 'digital'],
    mood:     'innovative, clean, futuristic, confident',
    designLevel: 'futuristic',
    palette: {
      primary:       '#5B5BD6',
      secondary:     '#8B5CF6',
      accent:        '#06B6D4',
      background:    '#FAFAFE',
      surface:       '#F1F2FF',
      surfaceAlt:    '#E8E9FE',
      textPrimary:   '#09090F',
      textSecondary: '#3730A3',
      mutedText:     '#6B6BA8',
      border:        '#D4D4F8',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(91,91,214,0.90) 0%, rgba(139,92,246,0.82) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F1F2FF 0%, #FAFAFE 100%)',
      accentWash:  'linear-gradient(135deg, #E8E9FE 0%, #F1F2FF 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(9,9,15,0.72) 0%, rgba(9,9,15,0.42) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(250,250,254,0.78) 0%, rgba(250,250,254,0.42) 100%)',
    },
    typography: {
      headingFontCategory: 'modern',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Inter', 'Helvetica Neue', sans-serif",
      bodyFontStack:       "'Inter', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.025em',
      lineHeight:          '1.6',
    },
    radius:  { card: '1rem',    button: '0.625rem', image: '1rem',   section: '0' },
    shadows: {
      card:     '0 2px 16px rgba(91,91,214,0.09)',
      floating: '0 8px 36px rgba(91,91,214,0.16)',
      image:    '0 12px 44px rgba(9,9,15,0.12)',
      button:   '0 4px 16px rgba(91,91,214,0.30)',
    },
    layout: {
      maxWidth:              '1280px',
      sectionPaddingDesktop: '6rem 1.5rem',
      sectionPaddingMobile:  '4rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'layered',
      dividerStyle:       'fade',
      backgroundStrategy: 'continuous_gradient',
    },
  },
  {
    category: 'SaaS',
    aliases:  ['saas', 'software as a service', 'platform', 'product', 'b2b'],
    mood:     'clean, trustworthy, modern, efficient',
    designLevel: 'futuristic',
    palette: {
      primary:       '#2563EB',
      secondary:     '#7C3AED',
      accent:        '#10B981',
      background:    '#FAFCFF',
      surface:       '#EFF6FF',
      surfaceAlt:    '#DBEAFE',
      textPrimary:   '#070E20',
      textSecondary: '#1D4ED8',
      mutedText:     '#6080B0',
      border:        '#BFDBFE',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(37,99,235,0.90) 0%, rgba(124,58,237,0.82) 100%)',
      sectionSoft: 'linear-gradient(180deg, #EFF6FF 0%, #FAFCFF 100%)',
      accentWash:  'linear-gradient(135deg, #DBEAFE 0%, #EFF6FF 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(7,14,32,0.72) 0%, rgba(7,14,32,0.42) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(250,252,255,0.78) 0%, rgba(250,252,255,0.42) 100%)',
    },
    typography: {
      headingFontCategory: 'modern',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Inter', 'Helvetica Neue', sans-serif",
      bodyFontStack:       "'Inter', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.025em',
      lineHeight:          '1.6',
    },
    radius:  { card: '0.875rem', button: '0.5rem', image: '0.875rem', section: '0' },
    shadows: {
      card:     '0 2px 14px rgba(37,99,235,0.08)',
      floating: '0 8px 36px rgba(37,99,235,0.15)',
      image:    '0 12px 44px rgba(7,14,32,0.12)',
      button:   '0 4px 16px rgba(37,99,235,0.28)',
    },
    layout: {
      maxWidth:              '1280px',
      sectionPaddingDesktop: '6rem 1.5rem',
      sectionPaddingMobile:  '4rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'layered',
      dividerStyle:       'fade',
      backgroundStrategy: 'continuous_gradient',
    },
  },

  // ── Luxury ─────────────────────────────────────────────────────────────────
  {
    category: 'luxury',
    aliases:  ['high-end', 'premium', 'prestige', 'exclusive', 'couture', 'bespoke'],
    mood:     'refined, exclusive, elegant, timeless',
    designLevel: 'luxury',
    palette: {
      primary:       '#1A1A1A',
      secondary:     '#6B5B3E',
      accent:        '#C9A84C',
      background:    '#FDFCF9',
      surface:       '#F5F2EB',
      surfaceAlt:    '#ECE7DB',
      textPrimary:   '#0A0A0A',
      textSecondary: '#4A3F2E',
      mutedText:     '#8A7A60',
      border:        '#D8CEBC',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(26,26,26,0.88) 0%, rgba(107,91,62,0.78) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F5F2EB 0%, #FDFCF9 100%)',
      accentWash:  'linear-gradient(135deg, #ECE7DB 0%, #F5F2EB 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(10,10,10,0.72) 0%, rgba(10,10,10,0.42) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(253,252,249,0.82) 0%, rgba(253,252,249,0.48) 100%)',
    },
    typography: {
      headingFontCategory: 'editorial',
      bodyFontCategory:    'serif',
      headingFontStack:    "'Cormorant Garamond', 'Garamond', 'Georgia', serif",
      bodyFontStack:       "'EB Garamond', 'Georgia', serif",
      headingWeight:       500,
      letterSpacing:       '0.04em',
      lineHeight:          '1.85',
    },
    radius:  { card: '0.25rem', button: '0.25rem', image: '0.5rem', section: '0' },
    shadows: {
      card:     '0 4px 28px rgba(10,10,10,0.07)',
      floating: '0 12px 48px rgba(10,10,10,0.14)',
      image:    '0 20px 60px rgba(10,10,10,0.16)',
      button:   '0 4px 14px rgba(10,10,10,0.16)',
    },
    layout: {
      maxWidth:              '1120px',
      sectionPaddingDesktop: '8rem 1.5rem',
      sectionPaddingMobile:  '5rem 1.25rem',
      verticalRhythm:        'luxury',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'editorial',
      dividerStyle:       'fade',
      backgroundStrategy: 'layered_surfaces',
    },
  },

  // ── Real Estate ────────────────────────────────────────────────────────────
  {
    category: 'real estate',
    aliases:  ['realtor', 'property', 'homes', 'realty', 'broker', 'agent'],
    mood:     'professional, aspirational, trustworthy, modern',
    designLevel: 'premium',
    palette: {
      primary:       '#1B4B8A',
      secondary:     '#2D7DD2',
      accent:        '#E8B23A',
      background:    '#F8FAFB',
      surface:       '#EEF3F8',
      surfaceAlt:    '#E0EAF2',
      textPrimary:   '#0A1929',
      textSecondary: '#1D3A5C',
      mutedText:     '#5A7898',
      border:        '#C8D8E8',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(27,75,138,0.86) 0%, rgba(45,125,210,0.76) 100%)',
      sectionSoft: 'linear-gradient(180deg, #EEF3F8 0%, #F8FAFB 100%)',
      accentWash:  'linear-gradient(135deg, #E0EAF2 0%, #EEF3F8 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(10,25,41,0.70) 0%, rgba(10,25,41,0.42) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(248,250,251,0.75) 0%, rgba(248,250,251,0.40) 100%)',
    },
    typography: {
      headingFontCategory: 'serif',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Playfair Display', 'Georgia', serif",
      bodyFontStack:       "'Source Sans Pro', 'Helvetica Neue', sans-serif",
      headingWeight:       700,
      letterSpacing:       '-0.01em',
      lineHeight:          '1.65',
    },
    radius:  { card: '0.75rem', button: '0.5rem', image: '0.875rem', section: '0' },
    shadows: {
      card:     '0 2px 16px rgba(10,25,41,0.08)',
      floating: '0 8px 36px rgba(10,25,41,0.14)',
      image:    '0 14px 48px rgba(10,25,41,0.16)',
      button:   '0 4px 14px rgba(27,75,138,0.24)',
    },
    layout: {
      maxWidth:              '1280px',
      sectionPaddingDesktop: '5.5rem 1.5rem',
      sectionPaddingMobile:  '3.5rem 1.25rem',
      verticalRhythm:        'balanced',
      cardDensity:           'balanced',
    },
    sectionFlow: {
      style:              'layered',
      dividerStyle:       'angle',
      backgroundStrategy: 'layered_surfaces',
    },
  },

  // ── Photography ────────────────────────────────────────────────────────────
  {
    category: 'photography',
    aliases:  ['photographer', 'photo studio', 'videography', 'cinematography', 'portrait'],
    mood:     'artistic, editorial, minimal, expressive',
    designLevel: 'editorial',
    palette: {
      primary:       '#1A1A1A',
      secondary:     '#444444',
      accent:        '#D4AF37',
      background:    '#FFFFFF',
      surface:       '#F5F5F5',
      surfaceAlt:    '#EBEBEB',
      textPrimary:   '#111111',
      textSecondary: '#333333',
      mutedText:     '#777777',
      border:        '#E0E0E0',
    },
    gradients: {
      hero:        'linear-gradient(135deg, rgba(26,26,26,0.80) 0%, rgba(68,68,68,0.65) 100%)',
      sectionSoft: 'linear-gradient(180deg, #F5F5F5 0%, #FFFFFF 100%)',
      accentWash:  'linear-gradient(135deg, #EBEBEB 0%, #F5F5F5 100%)',
      overlayDark: 'linear-gradient(to bottom, rgba(17,17,17,0.68) 0%, rgba(17,17,17,0.38) 100%)',
      overlayLight:'linear-gradient(to bottom, rgba(255,255,255,0.72) 0%, rgba(255,255,255,0.38) 100%)',
    },
    typography: {
      headingFontCategory: 'editorial',
      bodyFontCategory:    'sans',
      headingFontStack:    "'Cormorant Garamond', 'Georgia', serif",
      bodyFontStack:       "'Helvetica Neue', 'Arial', sans-serif",
      headingWeight:       500,
      letterSpacing:       '0.04em',
      lineHeight:          '1.75',
    },
    radius:  { card: '0.25rem', button: '0.25rem', image: '0.5rem', section: '0' },
    shadows: {
      card:     '0 2px 12px rgba(17,17,17,0.06)',
      floating: '0 8px 32px rgba(17,17,17,0.12)',
      image:    '0 16px 56px rgba(17,17,17,0.18)',
      button:   '0 2px 8px rgba(17,17,17,0.14)',
    },
    layout: {
      maxWidth:              '1400px',
      sectionPaddingDesktop: '6rem 1.5rem',
      sectionPaddingMobile:  '4rem 1.25rem',
      verticalRhythm:        'luxury',
      cardDensity:           'spacious',
    },
    sectionFlow: {
      style:              'editorial',
      dividerStyle:       'none',
      backgroundStrategy: 'alternating_soft',
    },
  },
]

// ── Default fallback preset ───────────────────────────────────────────────────

export const DEFAULT_PRESET: CategoryPreset = {
  category:    'default',
  aliases:     [],
  mood:        'professional, clean, modern',
  designLevel: 'clean',
  palette: {
    primary:       '#2563EB',
    secondary:     '#7C3AED',
    accent:        '#059669',
    background:    '#FAFBFF',
    surface:       '#F1F4FD',
    surfaceAlt:    '#E5E9F8',
    textPrimary:   '#080F20',
    textSecondary: '#1E3A8A',
    mutedText:     '#60748C',
    border:        '#CBD5E1',
  },
  gradients: {
    hero:        'linear-gradient(135deg, rgba(37,99,235,0.88) 0%, rgba(124,58,237,0.78) 100%)',
    sectionSoft: 'linear-gradient(180deg, #F1F4FD 0%, #FAFBFF 100%)',
    accentWash:  'linear-gradient(135deg, #E5E9F8 0%, #F1F4FD 100%)',
    overlayDark: 'linear-gradient(to bottom, rgba(8,15,32,0.68) 0%, rgba(8,15,32,0.40) 100%)',
    overlayLight:'linear-gradient(to bottom, rgba(250,251,255,0.78) 0%, rgba(250,251,255,0.42) 100%)',
  },
  typography: {
    headingFontCategory: 'sans',
    bodyFontCategory:    'sans',
    headingFontStack:    "'Inter', 'Helvetica Neue', sans-serif",
    bodyFontStack:       "'Inter', 'Helvetica Neue', sans-serif",
    headingWeight:       700,
    letterSpacing:       '-0.02em',
    lineHeight:          '1.65',
  },
  radius:  { card: '0.875rem', button: '0.5rem', image: '1rem', section: '0' },
  shadows: {
    card:     '0 2px 14px rgba(8,15,32,0.07)',
    floating: '0 8px 36px rgba(8,15,32,0.13)',
    image:    '0 12px 44px rgba(8,15,32,0.12)',
    button:   '0 4px 16px rgba(37,99,235,0.25)',
  },
  layout: {
    maxWidth:              '1200px',
    sectionPaddingDesktop: '5.5rem 1.5rem',
    sectionPaddingMobile:  '3.5rem 1.25rem',
    verticalRhythm:        'balanced',
    cardDensity:           'balanced',
  },
  sectionFlow: {
    style:              'soft_blend',
    dividerStyle:       'curve',
    backgroundStrategy: 'alternating_soft',
  },
}

// ── Lookup ────────────────────────────────────────────────────────────────────

/**
 * Find the best matching preset for a business type string.
 * Uses exact match first, then alias match, then keyword search.
 */
export function getCategoryPreset(businessType: string | null | undefined): CategoryPreset {
  if (!businessType) return DEFAULT_PRESET

  const lower = businessType.toLowerCase().trim()

  // Exact match
  const exact = PRESETS.find((p) => p.category.toLowerCase() === lower)
  if (exact) return exact

  // Alias match
  const alias = PRESETS.find((p) =>
    p.aliases.some((a) => a.toLowerCase() === lower || lower.includes(a.toLowerCase()))
  )
  if (alias) return alias

  // Partial category name match
  const partial = PRESETS.find((p) => lower.includes(p.category.toLowerCase()) || p.category.toLowerCase().includes(lower))
  if (partial) return partial

  return DEFAULT_PRESET
}
